# ********RoostGPT********
"""
Test generated by RoostGPT for test python using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219

ROOST_METHOD_HASH=gen_sequence_2ee21c9d2c
ROOST_METHOD_SIG_HASH=gen_sequence_067eac5e9e


# Test Scenarios for `gen_sequence` Function

Based on the provided function `gen_sequence`, I've developed the following test scenarios to validate its business logic:

## Scenario 1: Generate Sequence with All Character Types Enabled
**Details:**
  **TestName:** test_all_character_types_enabled
  **Description:** Verify that when all conditions are set to True, the function returns a sequence containing all possible character types (lowercase, uppercase, digits, and punctuation).

**Execution:**
  **Arrange:** Prepare a list of conditions with all values set to True: [True, True, True, True]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence contains all character types by checking if it includes lowercase letters, uppercase letters, digits, and punctuation

**Validation:**
  This test ensures the core functionality works correctly when all character types are requested. It validates that the function properly combines all character sets when all conditions are True.

## Scenario 2: Generate Sequence with No Character Types Enabled
**Details:**
  **TestName:** test_no_character_types_enabled
  **Description:** Verify that when all conditions are set to False, the function returns an empty string.

**Execution:**
  **Arrange:** Prepare a list of conditions with all values set to False: [False, False, False, False]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence is an empty string

**Validation:**
  This test validates the edge case where no character types are requested, ensuring the function behaves as expected by returning an empty string.

## Scenario 3: Generate Sequence with Only Lowercase Letters
**Details:**
  **TestName:** test_only_lowercase_enabled
  **Description:** Verify that when only the lowercase condition is True, the function returns a sequence containing only lowercase letters.

**Execution:**
  **Arrange:** Prepare a list of conditions with only the first value set to True: [True, False, False, False]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence contains only lowercase letters by checking if it equals string.ascii_lowercase

**Validation:**
  This test ensures that the function correctly handles a single character type selection, specifically lowercase letters, validating the selective inclusion logic.

## Scenario 4: Generate Sequence with Only Uppercase Letters
**Details:**
  **TestName:** test_only_uppercase_enabled
  **Description:** Verify that when only the uppercase condition is True, the function returns a sequence containing only uppercase letters.

**Execution:**
  **Arrange:** Prepare a list of conditions with only the second value set to True: [False, True, False, False]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence contains only uppercase letters by checking if it equals string.ascii_uppercase

**Validation:**
  This test validates the function's ability to correctly handle the selection of only uppercase letters, ensuring the character set mapping works as expected.

## Scenario 5: Generate Sequence with Only Digits
**Details:**
  **TestName:** test_only_digits_enabled
  **Description:** Verify that when only the digits condition is True, the function returns a sequence containing only digits.

**Execution:**
  **Arrange:** Prepare a list of conditions with only the third value set to True: [False, False, True, False]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence contains only digits by checking if it equals string.digits

**Validation:**
  This test ensures the function correctly handles the selection of only digits, validating another specific character type selection.

## Scenario 6: Generate Sequence with Only Punctuation
**Details:**
  **TestName:** test_only_punctuation_enabled
  **Description:** Verify that when only the punctuation condition is True, the function returns a sequence containing only punctuation characters.

**Execution:**
  **Arrange:** Prepare a list of conditions with only the fourth value set to True: [False, False, False, True]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence contains only punctuation characters by checking if it equals string.punctuation

**Validation:**
  This test validates the function's ability to correctly handle the selection of only punctuation characters, ensuring another specific character type selection works as expected.

## Scenario 7: Generate Sequence with Multiple Character Types
**Details:**
  **TestName:** test_multiple_character_types_enabled
  **Description:** Verify that when multiple conditions are set to True, the function returns a sequence containing the corresponding character types.

**Execution:**
  **Arrange:** Prepare a list of conditions with multiple values set to True: [True, False, True, False]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the returned sequence contains only lowercase letters and digits by checking if it equals string.ascii_lowercase + string.digits

**Validation:**
  This test ensures the function correctly combines multiple character types when multiple conditions are True, validating the core concatenation logic.

## Scenario 8: Handle Conditions List with Incorrect Length
**Details:**
  **TestName:** test_conditions_list_incorrect_length
  **Description:** Verify the function's behavior when the conditions list has a different length than the possible_characters list.

**Execution:**
  **Arrange:** Prepare a list of conditions with fewer or more elements than the possible_characters list: [True, False, True]
  **Act:** Call gen_sequence with the prepared conditions
  **Assert:** Verify that the function either handles this gracefully or raises an appropriate exception

**Validation:**
  This test validates how the function handles an edge case where the input doesn't match the expected format, ensuring robust error handling or graceful degradation.
"""

# ********RoostGPT********
import pytest
import string as str

from Password_Generator.pass_gen import PasswordGenerator


class TestPasswordGeneratorGenSequence:
    """Test suite for the gen_sequence method of PasswordGenerator class."""

    def test_all_character_types_enabled(self):
        """Test when all character types are enabled."""
        # Arrange
        conditions = [True, True, True, True]
        expected_sequence = str.ascii_lowercase + str.ascii_uppercase + str.digits + str.punctuation
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == expected_sequence, f"Expected '{expected_sequence}', but got '{result}'"
        
        # Verify all character types are present
        assert all(char in result for char in str.ascii_lowercase), "Missing lowercase characters"
        assert all(char in result for char in str.ascii_uppercase), "Missing uppercase characters"
        assert all(char in result for char in str.digits), "Missing digits"
        assert all(char in result for char in str.punctuation), "Missing punctuation"

    def test_no_character_types_enabled(self):
        """Test when no character types are enabled."""
        # Arrange
        conditions = [False, False, False, False]
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == "", f"Expected empty string, but got '{result}'"

    def test_only_lowercase_enabled(self):
        """Test when only lowercase letters are enabled."""
        # Arrange
        conditions = [True, False, False, False]
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == str.ascii_lowercase, f"Expected '{str.ascii_lowercase}', but got '{result}'"

    def test_only_uppercase_enabled(self):
        """Test when only uppercase letters are enabled."""
        # Arrange
        conditions = [False, True, False, False]
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == str.ascii_uppercase, f"Expected '{str.ascii_uppercase}', but got '{result}'"

    def test_only_digits_enabled(self):
        """Test when only digits are enabled."""
        # Arrange
        conditions = [False, False, True, False]
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == str.digits, f"Expected '{str.digits}', but got '{result}'"

    def test_only_punctuation_enabled(self):
        """Test when only punctuation is enabled."""
        # Arrange
        conditions = [False, False, False, True]
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == str.punctuation, f"Expected '{str.punctuation}', but got '{result}'"

    def test_multiple_character_types_enabled(self):
        """Test when multiple character types are enabled."""
        # Arrange
        conditions = [True, False, True, False]
        expected_sequence = str.ascii_lowercase + str.digits
        
        # Act
        result = PasswordGenerator.gen_sequence(conditions)
        
        # Assert
        assert result == expected_sequence, f"Expected '{expected_sequence}', but got '{result}'"

    def test_conditions_list_incorrect_length(self):
        """Test behavior when conditions list has incorrect length."""
        # Arrange
        conditions_too_short = [True, False, True]  # Missing one condition
        conditions_too_long = [True, False, True, False, True]  # Extra condition
        
        # Act & Assert - Test with too short conditions
        try:
            result = PasswordGenerator.gen_sequence(conditions_too_short)
            # If no exception is raised, the function should handle it gracefully
            # We can check if the result contains only the character types that were specified
            expected = str.ascii_lowercase + str.digits
            assert result == expected, f"Expected '{expected}', but got '{result}'"
        except IndexError:
            # This is also acceptable if the function doesn't handle incorrect input sizes
            pass
        
        # Act & Assert - Test with too long conditions
        try:
            result = PasswordGenerator.gen_sequence(conditions_too_long)
            # If no exception is raised, the function should use only the first 4 conditions
            expected = str.ascii_lowercase + str.digits
            assert result == expected, f"Expected '{expected}', but got '{result}'"
        except IndexError:
            # This is also acceptable if the function doesn't handle incorrect input sizes
            pass
